---
title: "Bioconductor Notes"
date: "2022-11-09"
abstract: >
  We discuss events related to the release of Bioconductor 3.16.
draft: true
author:  
  - name: Bioconductor Core Developer Team
    affiliation: Dana-Farber Cancer Institute, Roswell Park Comprehensive Cancer Center, City University of New York, Fred Hutchinson Cancer Research Center, Mass General Brigham
type: article
output: 
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

# Introduction 

[Bioconductor](https://bioconductor.org) provides
tools for the analysis and comprehension of high-throughput genomic
data.  The project has entered its twentieth year, with funding
for core development and infrastructure maintenance secured
through 2025 (NIH NHGRI 2U24HG004059).  Additional support is provided
by NIH NCI, Chan-Zuckerberg Initiative, National Science Foundation,
Microsoft, and Amazon.  In this news report, we give some
details about the software and data resource collection,
infrastructure for building, checking, and distributing resources,
core team activities, and some new initiatives.
 
# Software

Bioconductor 3.16 was released on 2 November, 2022. It is
compatible with R 4.2 and consists of 2183 software packages, 416
experiment data packages, 909 up-to-date annotation packages, 28
workflows, and 3 books. \href{https://bioconductor.org/books/release/}{Books} are
built regularly from source and therefore fully
reproducible; an example is the
community-developed [Orchestrating Single-Cell Analysis with Bioconductor](https://bioconductor.org/books/release/OSCA/).
The Bioconductor 
[3.16 release announcement](https://bioconductor.org/news/bioc_3_16_release/)
includes descriptions of 71 new software packages, 9 new data
  experiment packages, 2 new annotation packages, and updates to NEWS files for
  many additional packages. 

# Core team updates


- New developer Robert Shear of the
Department of Data Science at Dana-Farber Cancer
Institute has joined the Bioconductor Core Developer Team.
- Robert is joined by long-term core members Lori Kern of Roswell Park
Comprehensive Cancer Center, Marcel Ramos of CUNY and Roswell, Herv\'e Pages of
Fred Hutchinson Cancer Research Center, Jennifer Wokaty of CUNY, and Alex
Mahmoud at Channing Division of Network Medicine.


# Using Bioconductor

Start using
Bioconductor by installing the most recent version of R and evaluating
the commands
```
  if (!requireNamespace("BiocManager", quietly = TRUE))
      install.packages("BiocManager")
  BiocManager::install()
```

Install additional packages and dependencies,
e.g., [SingleCellExperiment](https://bioconductor.org/packages/SingleCellExperiment), with
```
  BiocManager::install("SingleCellExperiment")
```
[Docker](https://bioconductor.org/help/docker/)
images provides a very effective on-ramp for power users to rapidly
obtain access to standardized and scalable computing environments.
Key resources include:


- [bioconductor.org](https://bioconductor.org) to install,
  learn, use, and develop Bioconductor packages.
- A list of [available software](https://bioconductor.org/packages)
  linking to pages describing each package.
- A question-and-answer style
  [user support site](https://support.bioconductor.org) and
  developer-oriented [mailing list](https://stat.ethz.ch/mailman/listinfo/bioc-devel).
- A community slack ([sign up](https://slack.bioconductor.org))
   for extended technical discussion.
- The [F1000Research Bioconductor channel](https://f1000research.com/channels/bioconductor)
for peer-reviewed Bioconductor work flows.
- The [Bioconductor YouTube](https://www.youtube.com/user/bioconductor)
     channel includes recordings of keynote and talks from recent 
     conferences including Bioc2022, EuroBioC2022, and BiocAsia2021, in addition to 
     video recordings of training courses. 
- Our [package submission](https://github.com/Bioconductor/Contributions)
  repository for open technical review of new packages.

Upcoming and recently completed conferences are browsable at our
[events page](https://bioconductor.org/help/events/).

The [Technical](https://bioconductor.org/about/technical-advisory-board/)
and and [Community](https://bioconductor.org/about/community-advisory-board/)
Advisory Boards provide guidance to ensure that the project addresses
leading-edge biological problems with advanced technical approaches,
and adopts practices (such as a
project-wide [Code of Conduct](https://bioconductor.org/about/code-of-conduct/)
that encourages all to participate. We look forward to
welcoming you!

\address{Bioconductor Core Team \\
    Channing Division of Network Medicine \\
    Mass General Brigham \\
    Harvard Medical School, Boston, MA \\ \\
    Department of Data Science \\
    Dana-Farber Cancer Institute \\
    Harvard Medical School, Boston, MA \\ \\
    Biostatistics and Bioinformatics \\
    Roswell Park Comprehensive Cancer Center, Buffalo, NY \\ \\
    Fred Hutchinson Cancer Research Center, Seatlle, WA \\ \\
    CUNY Graduate School of Public Health, New York, NY}


